# arguments for dataset
dataset  : sythetic
crop_size: 518
data_root: /your/data/root

dataset_u  : sa1b
crop_size_u: 518
data_root_u: /your/data/root

dataset_val  : kitti
crop_size    : 518
data_root_val: /your/data/root/kitti_dataset
depth_min_val: 0.00001
depth_cap_val: 80

dataset_val_nyu  : nyu
crop_size_nyu    : 518
data_root_nyu    : /your/data/root/nyu/NYU_v2/rawdata_val/test
depth_min_val_nyu: 0.00001
depth_cap_val_nyu: 10

dataset_val_sintel  : sintel
crop_size_sintel    : 518
data_root_sintel    : /your/data/root/Sintel/training/
depth_min_val_sintel: 0.00001
depth_cap_val_sintel: 80

dataset_val_DIODE  : DIODE
crop_size_DIODE    : 518
data_root_DIODE    : /your/data/root/DIODE/val
depth_min_val_DIODE: 0.00001
depth_cap_val_DIODE: 80

dataset_val_ETH3D  : ETH3D
crop_size_ETH3D    : 518
data_root_ETH3D    : /your/data/root/ETH3D
depth_min_val_ETH3D: 0.1
depth_cap_val_ETH3D: 200



dataset_val_robotcar: robotcar
crop_size_robotcar: 518
data_root_robotcar: /your/data/root/robot/test
depth_min_val_robotcar: 0.00001
depth_cap_val_robotcar: 80

dataset_val_nuscene: nuscene
crop_size_nuscene: 518
data_root_nuscene: /your/data/root/nuscene/test_night
depth_min_val_nuscene: 0.00001
depth_cap_val_nuscene: 80


dataset_val_foggy: drive_foggy
crop_size_foggy: 518
data_root_foggy: /your/data/root/drivingstereo
depth_min_val_foggy: 0.00001
depth_cap_val_foggy: 80

dataset_val_cloudy: drive_cloudy
crop_size_cloudy: 518
data_root_cloudy: /your/data/root/drivingstereo
depth_min_val_cloudy: 0.00001
depth_cap_val_cloudy: 80


dataset_val_rainy: drive_rainy
crop_size_rainy: 518
data_root_rainy: /your/data/root/drivingstereo
depth_min_val_rainy: 0.00001
depth_cap_val_rainy: 80

dataset_val_kitti_c_fog: kitti_c_fog
crop_size_kitti_c_fog: 518
data_root_kitti_c_fog: /your/data/root/depth
depth_min_val_kitti_c_fog: 0.00001
depth_cap_val_kitti_c_fog: 80

dataset_val_kitti_c_snow: kitti_c_snow
crop_size_kitti_c_snow: 518
data_root_kitti_c_snow: /your/data/root/depth
depth_min_val_kitti_c_snow: 0.00001
depth_cap_val_kitti_c_snow: 80

dataset_val_kitti_c_dark: kitti_c_dark
crop_size_kitti_c_dark: 518
data_root_kitti_c_dark: /your/data/root/depth
depth_min_val_kitti_c_dark: 0.00001
depth_cap_val_kitti_c_dark: 80

dataset_val_kitti_c_motion: kitti_c_motion
crop_size_kitti_c_motion: 518
data_root_kitti_c_motion: /your/data/root/depth
depth_min_val_kitti_c_motion: 0.00001
depth_cap_val_kitti_c_motion: 80

dataset_val_kitti_c_gaussian: kitti_c_gaussian
crop_size_kitti_c_gaussian: 518
data_root_kitti_c_gaussian: /your/data/root/depth
depth_min_val_kitti_c_gaussian: 0.00001
depth_cap_val_kitti_c_gaussian: 80

dataset_val_DA2K: DA2K
crop_size_DA2K: 518
data_root_DA2K: /your/data/root/DA2K/DA-2K
depth_min_val_DA2K: 0.00001
depth_cap_val_DA2K: 80

dataset_val_DA2K_dark: DA2K_dark
crop_size_DA2K_dark: 518
data_root_DA2K_dark: /your/data/root/DA2K/DA-2K
depth_min_val_DA2K_dark: 0.00001
depth_cap_val_DA2K_dark: 80

dataset_val_DA2K_snow: DA2K_snow
crop_size_DA2K_snow: 518
data_root_DA2K_snow: /your/data/root/DA2K/DA-2K
depth_min_val_DA2K_snow: 0.00001
depth_cap_val_DA2K_snow: 80

dataset_val_DA2K_fog: DA2K_fog
crop_size_DA2K_fog: 518
data_root_DA2K_fog: /your/data/root/DA2K/DA-2K
depth_min_val_DA2K_fog: 0.00001
depth_cap_val_DA2K_fog: 80

dataset_val_DA2K_blur: DA2K_blur
crop_size_DA2K_blur: 518
data_root_DA2K_blur: /your/data/root/DA2K/DA-2K
depth_min_val_DA2K_blur: 0.00001
depth_cap_val_DA2K_blur: 80

# arguments for training
epochs: 20
batch_size: 4
lr: 0.000005  # 4GPUs
lr_multi: 1.0
criterion:
  name: AffineInvariantLossV2
  kwargs:
    ignore_index: 255
    alpha: 0.0
thresh_init: 0.85

# arguments for model
backbone: vits_kd
pretrain: True
multi_grid: False
replace_stride_with_dilation: [False, True, True]
dilations: [12, 24, 36]

argu_mode: robo_depth


is_dark: True
is_fog: True
is_frost: False
is_snow: True
is_motion_blur: True
is_zoom_blur: True
is_contrast: True

severity_lower_dark: 1
severity_upper_dark: 5
severity_lower_fog: 1
severity_upper_fog: 3
severity_lower_frost: 1
severity_upper_frost: 1
severity_lower_snow: 1
severity_upper_snow: 2
severity_lower_motion_blur: 1
severity_upper_motion_blur: 3
severity_lower_zoom_blur: 1
severity_upper_zoom_blur: 3
severity_lower_contrast: 1
severity_upper_contrast: 3

no_argu: False

prob_zoom_blur: 0.1
prob_motion_blur: 0.1
prob_snow: 0.2
prob_frost: 0.2
prob_fog: 0.2
prob_contrast: 0.2

save_interval: 2000
check_mask: False

vis: True

loss_mode: prior
encoder_freeze: True

use_prior: True
prior_mode: teacher

val_init: True
